name: Deploy base infrastructure
on:
  push:
    branches:
      - main

env:
  AWS_REGION: {{aws_region}}

jobs:
  plan_and_apply:
    name: Plan and Apply
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Plan Terraform
        id: plan
        continue-on-error: false
        run: |
          terraform plan -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan          

      - name: Apply Terraform
        if: steps.plan.outcome == 'success'
        id: apply
        continue-on-error: false
        run: |
          terraform apply \
            -input=false \
            -no-color \
            tfplan 